name = "majazi"
main = "worker.js"
compatibility_date = "2026-07-15"

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "KV"
id = "72c23dba33b9423bb7233e77e2bc83ee"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "exam_db"
database_id = "9f7fda8d-ba1b-4ea9-941d-07c82e2414f8"

[[durable_objects.bindings]]
name = "EXAM_ROOM"
class_name = "ExamRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ExamRoom"]

[triggers]
crons = ["0 21 * * *"]
